maxLogLines flag for configuration
dgarlitt/karma-nyan-reporter pull request #25
Opened 2017-05-17 22:14 UTC by whyboris

Added a flag to user configuration to limit the number of lines of failed test to log

```
      // limit the number of lines of error shown
      // No error occurs if this limit is longer than 
      // the number of lines reported.
      maxLogLines: 5 // default is 9001
```

Warning, the `test.js` files have not been updated.

2017-05-18 18:47 UTC, dgarlitt requested changes
While I appreciate pull requests and will happily integrate changes, this implementation will require some additional work before it is complete. The `lib/nyanCat.js` file is responsible for using the set methods exported from `lib/data/types.js`. Also, the `maxLines` variable value should initialize as undefined and then check for a value before limiting the error lines. Additionally, test coverage needs to be provided for these changes to get merged.

2017-05-18 18:47 UTC, dgarlitt commented on lib/data/types.js
> +var maxLines = 9001;
change to `var maxLines;` and move down below the next `var` definition.

2017-05-18 18:47 UTC, dgarlitt commented on lib/data/types.js
> +  this.errors = this.errors.slice(0, maxLines);
Check for value before limiting error count:

```
if (maxLines) {
  this.errors = this.errors.slice(0, maxLines);
}
```

2017-05-18 18:47 UTC, dgarlitt commented on lib/data/types.js
> +exports.setMaxLogLines = function(maxLogLines) {
This method needs to be implemented in the `lib/nyanCat.js` file.

2017-05-19 04:29 UTC, whyboris commented on lib/data/types.js
> +  this.errors = this.errors.slice(0, maxLines);
I just realized I addressed this differently -- setting a default (of 42) on `nyanCat.js` and always calling the `setMaxLogLines` function. This way, maxLines is always set.

I suspect your suggestion is better -- removing the default number, and only running the `.slice` when `maxLines` is present.

Please let me know, and I'll happily update my PR with the second approach.

2017-05-19 04:32 UTC, whyboris commented
Please feel free to commandeer my PR and change whatever you see fit. 

I am unsure if some of the tests I added are very useful. Also I was unable to cover the `else` path on a conditional I wrote -- decreasing your branch coverage.

I'm happy to update the PR with more feedback from you; thank you for the explicit suggestions before.

2017-05-19 15:21 UTC, whyboris commented on README.md
> +      maxLogLines: 5 // default is 9001
This line would also need to be added to the `npm version` readme (for some reason that part is missing from the `package.json`.

Also the `9001` needs to be `42` -- or whatever the final PR code will settle on.

2017-05-19 21:08 UTC, dgarlitt requested changes

2017-05-19 21:08 UTC, dgarlitt commented on README.md
> +      maxLogLines: 5 // default is 9001
The default should just be unlimited.

2017-05-19 21:08 UTC, dgarlitt commented on lib/nyanCat.js
> +      maxLogLines: 42
`maxLogLines`  doesn't need to be defined here.

2017-05-19 21:08 UTC, dgarlitt commented on lib/nyanCat.js
> +  dataTypes.setMaxLogLines(self.options.maxLogLines);
Wrap this in a condition:

```
if (self.options.maxlogLines) {
  dataTypes.setMaxLogLines(self.options.maxLogLines);
}
```

2017-05-26 05:25 UTC, whyboris commented
I recommend closing this PR in lieu of https://github.com/dgarlitt/karma-nyan-reporter/pull/33

2017-06-09 15:22 UTC, closed without merging